### ISSUE TITLE
Archives on version control

### ISSUE THREAD

**Issue by valentinogrean** [cosmin0502/Laboratory#1]
Unacceptable commit; why upload an archive on a a version control system? Please commit sources.

**Comment by cosmin0502** [comment]
Bună ziua! Eu nu am înțeles exact ce trebuie sa fac cu acel github. Nu am lucrat niciodată și nici nu pot sa creez un request nou ca îmi permite. Ce ar trebui efectiv sa fac?Pe 22 iun. 2021 08:46, Valentin Ogrean ***@***.***> a scris:
Unacceptable commit; why upload an archive on a a version control system? Please commit sources.

**Comment by valentinogrean** [comment]
Sunt lucruri pe care le am discutat si invatat la laborator :) Te rog sa citesti cu atentie requirement urile si sa te uiti peste resurse. Ne putem auzi si la laborator, ultima sesiune este in 23.06

**Comment by cosmin0502** [comment]
Din motive personale, eu nu am participat la laboratoare si de aceea v-am intrebat
